### ISSUE TITLE
ChaCha20 only encrypts partial content, when invoked repeatedly

### ISSUE THREAD

**Issue by Florob** [hauleth/octavo#34]
The ChaCha20 implementation is broken in a way that repeatedly calling `ChaCha20::encrypt_stream()` skips some of the input bytes. Specifically this happens if any of the calls input parameters is not a multiple of the block size.

Here is a small example demonstrating this:

``` rust
extern crate octavo;

use octavo::crypto::stream::chacha20::ChaCha20;
use octavo::crypto::stream::StreamEncrypt;

fn main() {
    let mut s = ChaCha20::new(b"aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa", b"cccccccccccc");

    let a = [0u8; 63];
    let mut outa = [0u8; 63];
    let b = [0u8; 64];
    let mut outb = [0u8; 64];

    s.encrypt_stream(&a[..], &mut outa[..]);
    s.encrypt_stream(&b[..], &mut outb[..]);

    println!("{:?}", &outa[..]);
    println!("{:?}", &outb[..]);
}
```

Since there is absolutely no documentation, this could of course be intended behaviour. However, I would argue that this is a very common use-case with data received from a network connection.

**Comment by hauleth** [comment]
You are right, this is bug. I will try to fix that ASAP.

As for documentation, this is on go. Firstly I focus on functionality and then I will document everything. I see documentation as a very important in this library so I am really disappointed in myself as there is so much lack in documentation. I will do better.
