### ISSUE TITLE
Copy, Clone not implemented for digests

### ISSUE THREAD

**Issue by kryptan** [hauleth/octavo#57]
Other common traits might also be useful, such as `Eq`, `PartialEq`.

**Comment by hauleth** [comment]
It was done on purpose as `Eq` and `PartialEq` doesn't make sense in terms of digest. You should compare only result, not internal state of the function.

The same goes for `Copy` - there is no sense in this as you should not be able to copy partially computed hash into other context. Digests, although looks like structs, are de facto functions. Only reason why they aren't invoked as one is that sometimes it is impossible to read that much data at once (ex. computing checksum for backups which can be several hundreds of gigabytes).

Leaving open for now as there should be more than 1 opinion on that matter.

**Comment by kryptan** [comment]
What if I need to compute several hashes of different data with the same prefix?
I will first write common data into hasher and then copy it and write different data into different instances. Do you want me to rehash it from start each time?

openssl crate imlpements `Clone`: http://sfackler.github.io/rust-openssl/doc/v0.6.7/openssl/crypto/hash/struct.Hasher.html

As for `Eq` I don't have use case currently but I will think about it.

**Comment by hauleth** [comment]
Ok, `Clone` is only reasonable thing to add. I will think about it as this forces you to explicitly call `clone()` when needed.
