### ISSUE TITLE
Make digest pass tests for vectors from NIST for longer messages

### ISSUE THREAD

**Issue by silmeth** [hauleth/octavo#60]
Now SHA2 implementations do not pass all of the tests from NIST documents, they have problems with hashing messages longer than one block. Those longer test vectors can be found on:
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA224.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA256.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA384.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_224.pdf
- http://csrc.nist.gov/groups/ST/toolkit/documents/Examples/SHA512_256.pdf

Current implementation does not check those and when added, does not pass them for bigger hashes (SHA-384, SHA-512, and when added, SHA-512/224 and SHA-512/256).

**Comment by hauleth** [comment]
What is stranger, tests fails only for that one test. If I test against `1_000_000 * 'a'` result is valid.
