### ISSUE TITLE
WHIRPOOL returns invalid data

### ISSUE THREAD

**Issue by hauleth** [hauleth/octavo#98]

**Comment by ghost** [comment]
Your issue doesn't follow our guidelines. Please fix the following:
- Issue description cannot be empty [(?)](https://gitmagic.io/rules/#/issue/body-cannot-be-empty)

[Click here](https://app.gitmagic.io/libOctavo/octavo/98/a1563c4e-118f-4898-aa15-b6cd0fcd7cf3/a496f3e7-a1e1-421e-b053-d846961320d0) for details.

Thank you! :pray:
<sub>
This comment was made by [GitMagic](https://gitmagic.io/) – Magically enforcing your contribution guidelines.
</sub>
